/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ormac
 */
public class ListarVehiculosView extends javax.swing.JDialog {
    
    /**
     * Creates new form ListarVehiculosView
     */
    public ListarVehiculosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarVehiculos();
    }
    
    private void listarVehiculos(){
        ArrayList<VehiculoViewModel> vehiculos = Controlador.getVehiculos();
        vehiculosGrid.setModel(new DefaultTableModel(new Object[][] {}, 
            new String[] { "Patente","Marca","Vehículo", "Tipo", "Sucursal", "Cap.Carga", "Km/litro", "Año", "Litros extra", "Km a recorrer" }));
        
        for(VehiculoViewModel vehiculo : vehiculos){
            ((DefaultTableModel)vehiculosGrid.getModel()).addRow(new Object[] {
                vehiculo.getPatente(),
                vehiculo.getMarca(),
                vehiculo.getVehiculo(),
                vehiculo.getTipo(),
                vehiculo.getSucursal(),
                vehiculo.getCapacidadCarga(),
                vehiculo.getKmPorLitro(),
                vehiculo.getAnio(),
                vehiculo.getLitrosExtra(),
                vehiculo.getKmARecorrer()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vehiculosGrid = new javax.swing.JTable();
        calcularConsumos = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        totalConsumoElectricosValue = new javax.swing.JLabel();
        totalConsumoCombustibleLabel = new javax.swing.JLabel();
        totalConsumoElectricosLabel = new javax.swing.JLabel();
        totalConsumoCombustibleValue = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        vehiculosGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(vehiculosGrid);

        calcularConsumos.setText("Calcular Consumos");
        calcularConsumos.addActionListener(this::calcularConsumosActionPerformed);

        panel.setBackground(new java.awt.Color(0, 204, 204));

        totalConsumoElectricosValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalConsumoElectricosValue.setForeground(new java.awt.Color(255, 102, 51));
        totalConsumoElectricosValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalConsumoElectricosValue.setText("0");

        totalConsumoCombustibleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalConsumoCombustibleLabel.setText("Consumo Vehículos Combustible");

        totalConsumoElectricosLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalConsumoElectricosLabel.setText("Consumo Vehículos Eléctricos");

        totalConsumoCombustibleValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalConsumoCombustibleValue.setForeground(new java.awt.Color(0, 0, 153));
        totalConsumoCombustibleValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalConsumoCombustibleValue.setText("0");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalConsumoElectricosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalConsumoCombustibleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalConsumoElectricosValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalConsumoCombustibleValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalConsumoElectricosLabel)
                    .addComponent(totalConsumoElectricosValue))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalConsumoCombustibleLabel)
                    .addComponent(totalConsumoCombustibleValue))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calcularConsumos, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(calcularConsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularConsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularConsumosActionPerformed
        TableModel table = vehiculosGrid.getModel();
        Map<String, Double> lista = new HashMap<>();
        for(int i=0;i< table.getRowCount();i++){
            lista.put((String)table.getValueAt(i, 0), (Double)table.getValueAt(i, 9));
        }
        double[] consumos = Controlador.calcularConsumos(lista);
        totalConsumoElectricosValue.setText(String.format("%.2f%n kWh", consumos[0]));
        totalConsumoCombustibleValue.setText(String.format("%.2f%n litros", consumos[1]));
    }//GEN-LAST:event_calcularConsumosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularConsumos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton salir;
    private javax.swing.JLabel totalConsumoCombustibleLabel;
    private javax.swing.JLabel totalConsumoCombustibleValue;
    private javax.swing.JLabel totalConsumoElectricosLabel;
    private javax.swing.JLabel totalConsumoElectricosValue;
    private javax.swing.JTable vehiculosGrid;
    // End of variables declaration//GEN-END:variables
}
